# Generated by Django 3.2.5 on 2022-10-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221016_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
